# Generated by Django 4.2.1 on 2024-02-03 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('date_enrolled', models.DateField()),
                ('study_program_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.studyprogram')),
            ],
        ),
    ]
