# Generated by Django 4.2.1 on 2024-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='course_pictures/'),
        ),
    ]
