# Generated by Django 4.2.11 on 2024-03-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0003_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
