# Generated by Django 4.2.11 on 2024-03-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0004_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='study_program_enrolled',
            new_name='StudyProgram',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='location',
        ),
    ]
