# Generated by Django 4.2.11 on 2024-03-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0005_rename_study_program_enrolled_student_studyprogram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='StudyProgram',
            new_name='study_program',
        ),
    ]
