# Generated by Django 4.2.11 on 2024-03-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0007_student_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
    ]
