# Generated by Django 4.2.11 on 2024-03-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0008_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.studyprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.exam')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='papers',
            field=models.ManyToManyField(to='QuestionPaperapp.paper'),
        ),
    ]
