# Generated by Django 4.2.11 on 2024-03-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0009_exam_paper_student_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='papers',
        ),
    ]
