# Generated by Django 4.2.11 on 2024-03-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0010_remove_student_papers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
