# Generated by Django 4.2.11 on 2024-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0014_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='default_role_value', max_length=100),
        ),
    ]
