# Generated by Django 4.2.1 on 2024-04-14 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0016_alter_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('QuestionText', models.TextField()),
                ('Option1', models.CharField(max_length=255)),
                ('Option2', models.CharField(max_length=255)),
                ('Option3', models.CharField(max_length=255)),
                ('Option4', models.CharField(max_length=255)),
                ('CorrectOption', models.CharField(max_length=255)),
                ('DifficultyLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], max_length=10)),
                ('Weightage', models.IntegerField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.course')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.exam')),
            ],
        ),
    ]
