# Generated by Django 4.2.1 on 2024-04-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0017_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='paper_submissions/')),
                ('marks_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted')], default='Not Submitted', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuestionPaperapp.student')),
            ],
        ),
    ]
