# Generated by Django 4.2.1 on 2024-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0018_papersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='total_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='submission_status',
            field=models.CharField(choices=[('Marked', 'Marked'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Marked', max_length=20),
        ),
    ]
