# Generated by Django 4.2.1 on 2024-04-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestionPaperapp', '0019_papersubmission_comment_papersubmission_total_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='submission_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Not Submitted', 'Not Submitted'), ('Marked', 'Marked'), ('Pass', 'Pass'), ('Fail', 'Fail')], default='Submitted', max_length=20),
        ),
    ]
